# Generated by Django 4.1.3 on 2024-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0005_admin_information_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_information',
            name='lungs_ct',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
