# Generated by Django 5.0.6 on 2024-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0006_test_information_lungs_ct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_information',
            name='role',
            field=models.CharField(blank=True, choices=[('hospital', 'hospital'), ('laboratory', 'laboratory')], max_length=200, null=True),
        ),
    ]
