# Generated by Django 5.0.6 on 2024-06-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacist',
        ),
    ]
