# Generated by Django 5.0.6 on 2024-06-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='testcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='orderitems',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='receiving_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='referred_value',
        ),
        migrations.RemoveField(
            model_name='report',
            name='specimen_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='specimen_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Specimen',
        ),
        migrations.DeleteModel(
            name='testCart',
        ),
        migrations.DeleteModel(
            name='testOrder',
        ),
    ]
